# Generated by Django 4.1.7 on 2023-04-13 21:10

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('interest', models.TextField()),
                ('goal', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('fitness_goal', models.TextField()),
                ('current_plans', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=3)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_name', models.TextField()),
                ('description', models.TextField()),
                ('difficulty_level', models.TextField()),
                ('goal', models.TextField()),
                ('equipment', models.TextField()),
                ('training_part', models.TextField()),
            ],
        ),
    ]
