# Generated by Django 4.1.7 on 2023-04-13 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('interest', models.TextField()),
                ('goal', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('difficulty_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.IntegerField()),
                ('plan_name', models.TextField()),
                ('description', models.TextField()),
                ('difficulty_level', models.TextField()),
                ('goal', models.TextField()),
                ('equipment', models.TextField()),
                ('training_part', models.TextField()),
            ],
        ),
    ]
