# Generated by Django 4.1.7 on 2023-04-13 22:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_coach', '0003_alter_fituser_current_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fituser',
            name='current_plans',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=3),
        ),
    ]
